# Generated by Django 3.1.1 on 2020-09-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名称')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('age', models.CharField(max_length=20, verbose_name='年龄')),
                ('height', models.CharField(max_length=20, verbose_name='身高/cm')),
                ('weight', models.CharField(max_length=20, verbose_name='体重')),
                ('address', models.CharField(max_length=50, verbose_name='住址')),
                ('id_number', models.CharField(max_length=30, verbose_name='身份证号')),
                ('tel', models.CharField(max_length=20, verbose_name='电话号码')),
                ('edu_background', models.CharField(max_length=20, verbose_name='文化程度')),
                ('is_instructor', models.BooleanField(verbose_name='是否指导员')),
                ('instructor_class', models.CharField(max_length=20, verbose_name='指导员等级')),
                ('instructor_type', models.CharField(max_length=40, verbose_name='指导类型')),
                ('ver_status', models.CharField(max_length=20, verbose_name='审核状态')),
                ('city', models.CharField(max_length=20, verbose_name='市级区划')),
                ('district', models.CharField(max_length=20, verbose_name='县级区划')),
                ('village', models.CharField(max_length=20, verbose_name='乡镇')),
                ('certificate_num', models.CharField(max_length=50, verbose_name='证书编号')),
                ('certificate_date', models.CharField(max_length=20, verbose_name='发证日期')),
                ('gym', models.CharField(max_length=50, verbose_name='健身地点')),
                ('assessment', models.CharField(max_length=30, verbose_name='评定成绩')),
                ('upload_time', models.CharField(max_length=30, verbose_name='上传日期')),
                ('annual_survey_date', models.CharField(max_length=30, verbose_name='年检日期')),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=128, verbose_name='发布内容')),
                ('post_time', models.CharField(max_length=30, verbose_name='发布时间')),
                ('picture_path', models.CharField(max_length=128, verbose_name='图片路径')),
                ('location', models.CharField(max_length=128, verbose_name='定位')),
                ('title', models.CharField(max_length=50, verbose_name='话题/标签')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.userinfo', verbose_name='用户ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30, verbose_name='点赞时间')),
                ('like', models.ManyToManyField(to='users_management.UserInfo', verbose_name='点赞者')),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.moment', verbose_name='点赞动态ID')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=30, verbose_name='关注时间')),
                ('follow', models.ManyToManyField(to='users_management.UserInfo', verbose_name='关注者')),
                ('moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.moment', verbose_name='动态ID')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=800, verbose_name='反馈内容')),
                ('time', models.CharField(max_length=30, verbose_name='反馈时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.userinfo', verbose_name='反馈者')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('colletcor', models.ManyToManyField(to='users_management.UserInfo', verbose_name='收藏者')),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.moment', verbose_name='点赞动态ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=800, verbose_name='评论内容')),
                ('time', models.CharField(max_length=30, verbose_name='评论时间')),
                ('moment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.moment', verbose_name='动态ID')),
                ('user', models.ManyToManyField(to='users_management.UserInfo', verbose_name='评论者ID')),
            ],
        ),
    ]
