# Generated by Django 3.1.1 on 2020-09-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0003_auto_20200922_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
        migrations.AlterModelTable(
            name='favorite',
            table='favorite',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='feedback',
        ),
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
        migrations.AlterModelTable(
            name='like',
            table='like',
        ),
        migrations.AlterModelTable(
            name='moment',
            table='moment',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
