# Generated by Django 3.1.1 on 2020-09-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0006_auto_20200922_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_management.userinfo', verbose_name='用户ID'),
        ),
    ]
