# Generated by Django 3.1.1 on 2020-09-22 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0007_auto_20200922_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='access',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='moment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_management.userinfo', verbose_name='用户ID'),
        ),
    ]
