# Generated by Django 3.1.1 on 2020-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0012_access_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='annual_survey_date',
            field=models.DateField(max_length=30, null=True, verbose_name='年检日期'),
        ),
    ]
