# Generated by Django 3.1.1 on 2020-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0013_auto_20200925_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.IntegerField(max_length=20, null=True, verbose_name='年龄'),
        ),
    ]
