# Generated by Django 3.1.1 on 2020-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_management', '0015_auto_20200927_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moment',
            old_name='user_id',
            new_name='user',
        ),
    ]
